version: '3.9'

services:
  PostgreSQL:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gubee
      POSTGRES_PASSWORD: gubee
      PGDATA: /data/postgres
    volumes:
      - ./postgres-hero:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  API:
      image: 'codewhile/interview-dockerfile:latest'
      ports:
        - "8080:8080"
      environment:
        - JDBC_URL=jdbc:postgresql://PostgreSQL:5432/postgres
        - JDBC_USERNAME=gubee
        - JDBC_PASSWORD=gubee
        - JDBC_SCHEMA=interview_service
      depends_on:
        - PostgreSQL

