version: '3.9'

services:
  PostgreSQL:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gubee
      POSTGRES_PASSWORD: gubee
      PGDATA: /data/postgres
    volumes:
      - ./postgres-hero:/data/postgres
    ports:
      - "5432:5432"
    restart: always

